version: '3'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: j03p455N0R1
      DB_DATABASE: nest
      JWT_SECRET: 45345345345
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:latest
    ports:
      - "3377:3306"
    environment:
      MYSQL_ROOT_PASSWORD: j03p455N0R1
    volumes:
      - ./data:/var/lib/mysql  # Ganti dengan path direktori untuk data MySQL jika perlu
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql ke direktori initdb MySQL
