version: '3'

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nest

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    restart: always
    ports:
      - "3022:3000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://root:example@mongodb:27017
      DB_NAME: nest
    depends_on:
      - mongodb
